config/routes.rb
Rails.application.routes.draw do
  post 'new_reply', to: 'article_comments#new_reply', as: 'new_reply'
  resources :articles
  resources :article_comments
  root 'home#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_comments
  has_many :pictures, as: :imageable

  # validation
  validates :title, presence: true
  validates :content, presence: true



end

app/models/article_comment.rb
class ArticleComment < ApplicationRecord
  belongs_to :user
  belongs_to :article
  has_many :comment_reply, class_name: 'ArticleComment', foreign_key: 'parent_id'
  belongs_to :parent, class_name: 'ArticleComment', optional: true
end

app/models/picture.rb
class Picture < ApplicationRecord
	 belongs_to :imageable, polymorphic: true
	  mount_uploader :soft_pic, SoftPicUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# before_action :authenticate_user!
end

app/controllers/article_comments_controller.rb
class ArticleCommentsController < ApplicationController
	def create
		
		@article_comment = ArticleComment.new(comment: params[:comment],article_id: params[:article_id],user_id: current_user.id)
	     if params[:article_comment_id].present?
	    
	      @obj_article = ArticleComment.find (params[:article_comment_id])

	      @article_comment.article_id=@obj_article.article_id
	      @article_comment.parent_id=params[:article_comment_id]
	     end
	     @article_comment.save
		    respond_to do |format|
		    format.js{}
			end 
	end
	def new_reply
		respond_to do |format|
		  format.js{}
		end 
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id=current_user.id
    respond_to do |format|
      if @article.save
        Article.last.pictures.create(soft_pic: params[:article][:soft_pic])
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :user_id)
    end
end

app/controllers/comment_answer_controller.rb
class CommentAnswerController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@articles = Article.all.paginate(page: params[:page], per_page: 30)
  	@three_articles = Article.take(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_comments_helper.rb
module ArticleCommentsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comment_answer_helper.rb
module CommentAnswerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/article_comments/_comment.js.erb
 $('#article_comments').html("<%= j(render 'article_comments/comments.html')%>");
 // location.reload();

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<script type="text/javascript">
      $(document).ready(function () {
        // Setup - add a text input to each footer cell
        $('#my_datatable tfoot th').each(function () {
            var title = $(this).text();
            $(this).html('<input type="text" placeholder="Search ' + title + '" />');
        });

        // DataTable
        var table = $('#my_datatable').DataTable({
            "scrollX": true,

     "pageLength": 50,
          dom: 'Bfrtip',
      buttons: [
          'print'
      ]



        });

        // Apply the search
        table.columns().every(function () {
            var that = this;

            $('input', this.footer()).on('keyup change', function () {
                if (that.search() !== this.value) {
                    that
                        .search(this.value)
                        .draw();
                }
            });
        });
    });
</script>
<div class="container">
  <p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table id="my_datatable">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th>show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.content[0...50] %></td>
        <td><%= article.user.id %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
   <tfoot>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th>show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </tfoot>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div  class="alert alert-primary" role="alert">
   <p id="notice"><%= notice %></p> 
</div>





<section class="section single-wrapper">
            <div class="container">
                <div class="row">
                    <div class="col-lg-9 col-md-12 col-sm-12 col-xs-12">
                        <div class="page-wrapper">
                            <div class="blog-title-area text-center">
                                <ol class="breadcrumb hidden-xs-down">
                                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                                    <li class="breadcrumb-item"><a href="#">Blog</a></li>
                                    <li class="breadcrumb-item active">Top 10 phone applications and 2017 mobile design awards</li>
                                    <h1><%=@article.title%></h1>
                                </ol>

                                <span class="color-orange"><a href="tech-category-01.html" title="">Technology</a></span>

                                

                               

                               
                            </div><!-- end title -->

                            <div class="single-post-media">
                                 <%= image_tag(@article.pictures.first.soft_pic.url, size: "800x460")%>
                            </div><!-- end media -->

                            <div class="blog-content">  
                              

                                <img src="upload/tech_menu_09.jpg" alt="" class="img-fluid img-fullwidth">

                                  <div class="pp">
                                    <p><%=@article.content%></p>

                                </div><!-- end pp -->
                            </div><!-- end content -->

                            <div class="blog-title-area">
                                <div class="tag-cloud-single">
                                    <span>Tags</span>
                                    <small><a href="#" title="">lifestyle</a></small>
                                    <small><a href="#" title="">colorful</a></small>
                                    <small><a href="#" title="">trending</a></small>
                                    <small><a href="#" title="">another tag</a></small>
                                </div><!-- end meta -->

                                <div class="post-sharing">
                                    <ul class="list-inline">
                                        <li><a href="#" class="fb-button btn btn-primary"><i class="fa fa-facebook"></i> <span class="down-mobile">Share on Facebook</span></a></li>
                                        <li><a href="#" class="tw-button btn btn-primary"><i class="fa fa-twitter"></i> <span class="down-mobile">Tweet on Twitter</span></a></li>
                                        <li><a href="#" class="gp-button btn btn-primary"><i class="fa fa-google-plus"></i></a></li>
                                    </ul>
                                </div><!-- end post-sharing -->
                            </div><!-- end title -->

                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="banner-spot clearfix">
                                        <div class="banner-img">
                                            <img src="upload/banner_01.jpg" alt="" class="img-fluid">
                                        </div><!-- end banner-img -->
                                    </div><!-- end banner -->
                                </div><!-- end col -->
                            </div><!-- end row -->

                            <hr class="invis1">

                       

                            <hr class="invis1">

                            


                            

                            <hr class="invis1">

                            <div class="custombox clearfix">

                                <h4 class="small-title">Comments</h4>
                                
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="comments-list">
                                            
                                            <div class="media">
                                                <a class="media-left" href="#">
                                                    <img src="upload/author_01.jpg" alt="" class="rounded-circle">
                                                </a>
                                                <div class="media-body">

                                                    <h4 class="media-heading user_name">Baltej Singh <small>5 days ago</small></h4>

                                                    <p id="article_comments">
                                                    	<table>
 	                                                      <%@article.article_comments.where(parent_id: nil).each do |cmt|%>
                                                      		<tr>
                                                      			<td><%=cmt.comment%></td>
                                                      			<table style="margin-left: 30px;">
                                                      					<%cmt.comment_reply.each do |cmt_reply|%>
                                                      					<tr>
                                                      						<td><%=cmt_reply.comment%> </td>
                                                      					</tr>
                                                      					<%end%>
                                                      			</table>
                                                      				
                                                      				
                                                      			
                                                      			
                                                      			<td>
                                                      				<div id="<%=cmt.id%>"></div>
                                                      			</td>
                                                      			<td>
                                                      				<div id="myid"></div>
                                                      				<%= form_tag new_reply_path, remote: true, method: :post, id: "answer" do %>
                                                                
                                                      	          		<%= hidden_field_tag :article_comment_id, cmt.id%>
                                                      	          		 <%= button_tag 'reply', class: 'btn btn-primary',
                                                      	                           data: { disable_with: "<i class='fa fa-refresh fa-spin'>
                                                      	     			 </i> Submitting Changes..."} %>
                                                              		 <%end%>
                                                      			</td>
                                                      		</tr>
                                                       	<%end%>
                                                       </table>


                                                    </p>

                                                    
                                                </div>
                                            </div>
                                           
                                        </div>
                                    </div><!-- end col -->
                                </div><!-- end row -->
                            </div><!-- end custom-box -->

                            <hr class="invis1">

                            <div class="custombox clearfix">
                                <h4 class="small-title">Leave a Reply</h4>
                                <div class="row">
                                    <div class="col-lg-12">
                                       <!--  <form class="form-wrapper">
                                            <input type="text" class="form-control" placeholder="Your name">
                                            <input type="text" class="form-control" placeholder="Email address">
                                            <input type="text" class="form-control" placeholder="Website">
                                            <textarea class="form-control" placeholder="Your comment"></textarea>
                                            <button type="submit" class="btn btn-primary">Submit Comment</button>
                                        </form> -->
                                         <%= form_tag '/article_comments', remote: true, method: :post, id: "article_comment" do %>
									         <%= text_field_tag :comment, '', placeholder: "Type comment"%>
									         <%= hidden_field_tag :article_id, @article.id%>
									         <%= button_tag 'Submit', class: 'btn btn-primary',
									                           data: { disable_with: "<i class='fa fa-refresh fa-spin'>
									      		</i> Submitting Changes..."} %>
								         <%end%>

                                    </div>
                                </div>
                            </div>
                        </div><!-- end page-wrapper -->
                    </div><!-- end col -->
                </div><!-- end row -->
            </div><!-- end container -->
        </section>

                    

app/views/home/index.html.erb
<style type="text/css">
    .head_imgs{
            height: 300px !important;
    }
</style>
        <section class="section first-section">
            <div class="container-fluid">
                <div class="masonry-blog clearfix d-flex">
                    <%@three_articles.each do |article|%>
                     <div class="first-slot">
                        <div class="masonry-box post-media">
                              
                               <%= image_tag(article.pictures.first.soft_pic.url,class: 'head_imgs')%>
                             <div class="shadoweffect">
                                <div class="shadow-desc">
                                    <div class="blog-meta">
                                        <span class="bg-orange"><a href="tech-category-01.html" title="">Technology</a></span>
                                        <h4><a href="<%=article_path(article.id)%>" title=""><%=article.title%></a></h4>
                                        <small><a href="tech-single.html" title=""><%=article.created_at%></a></small>
                                        <small><a href="tech-author.html" title="">user ID# <%=article.user_id%></a></small>
                                    </div><!-- end meta -->
                                </div><!-- end shadow-desc -->
                            </div><!-- end shadow -->
                        </div><!-- end post-media -->
                    </div><!-- end first-side -->

                    <%end%>
                   

               

                    
                </div><!-- end masonry -->
            </div>
        </section>

        <section class="section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-9 col-md-12 col-sm-12 col-xs-12">
                        <div class="page-wrapper">
                            <div class="blog-top clearfix">
                                <h4 class="pull-left">Recent News <a href="#"><i class="fa fa-rss"></i></a></h4>
                            </div><!-- end blog-top -->

                            <div class="blog-list clearfix">
                                <%@articles.each do |article|%>
                                    <div class="blog-box row">
                                        <div class="col-md-4">
                                            <div class="post-media">

                                                <a href="<%= article_path(article.id) %>" title="">
                                                      <%= image_tag(article.pictures.first.soft_pic.url, size: "600x500",class: 'img-fluid')%>
                                                    <div class="hovereffect"></div>
                                                </a>
                                            </div><!-- end media -->
                                        </div><!-- end col -->

                                        <div class="blog-meta big-meta col-md-8">
                                            <h4><a href="<%=article_path(article.id)%>" title=""><%=article.title%></a></h4>
                                            <p><%=article.content%></p>
                                            <small class="firstsmall"><a class="bg-orange" href="tech-category-01.html" title="">Gadgets</a></small>
                                            <small><a href="tech-single.html" title=""><%=article.created_at%></a></small>
                                            <small><a href="tech-author.html" title="">USER#ID<%=article.user_id%></a></small>
                                            <small>

                                                <%if current_user.present? && (article.user_id==current_user.id)%>
                                                <%=link_to 'Edit',edit_article_path(article.id)%>
                                                <%end%>

                                            
                                            </small>
                                        </div><!-- end meta -->
                                    </div><!-- end blog-box -->
                                <%end%>
                                

                                <hr class="invis">
                            </div><!-- end blog-list -->
                        </div><!-- end page-wrapper -->

                        <hr class="invis">

                        <div class="row">
                            <div class="col-md-12">
                                <nav aria-label="Page navigation">
                                    <%= will_paginate @articles %>
                                    <!-- <ul class="pagination justify-content-start">
                                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                                        <li class="page-item">
                                            <a class="page-link" href="#">Next</a>
                                        </li>
                                    </ul> -->
                                </nav>
                            </div><!-- end col -->
                        </div><!-- end row -->
                    </div><!-- end col -->
                </div><!-- end row -->
            </div><!-- end container -->
        </section>

                    

        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7">
                        <div class="widget">
                            <div class="footer-text text-left">
                                <a href="index.html">
                                <%=image_tag('blog/tech-footer-logo.png',class: 'img-fluid ' )%></a>
                                <p>Tech Blog is a technology blog, we sharing marketing, news and gadget articles.</p>
                                <div class="social">
                                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Facebook"><i class="fa fa-facebook"></i></a>              
                                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Twitter"><i class="fa fa-twitter"></i></a>
                                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Instagram"><i class="fa fa-instagram"></i></a>
                                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Google Plus"><i class="fa fa-google-plus"></i></a>
                                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Pinterest"><i class="fa fa-pinterest"></i></a>
                                </div>

                                <hr class="invis">

                                <div class="newsletter-widget text-left">
                                    <form class="form-inline">
                                        <input type="text" class="form-control" placeholder="Enter your email address">
                                        <button type="submit" class="btn btn-primary">SUBMIT</button>
                                    </form>
                                </div><!-- end newsletter -->
                            </div><!-- end footer-text -->
                        </div><!-- end widget -->
                    </div><!-- end col -->

                    <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12">
                        <div class="widget">
                            <h2 class="widget-title">Popular Categories</h2>
                            <div class="link-widget">
                                <ul>
                                    <li><a href="#">Marketing <span>(21)</span></a></li>
                                    <li><a href="#">SEO Service <span>(15)</span></a></li>
                                    <li><a href="#">Digital Agency <span>(31)</span></a></li>
                                    <li><a href="#">Make Money <span>(22)</span></a></li>
                                    <li><a href="#">Blogging <span>(66)</span></a></li>
                                </ul>
                            </div><!-- end link-widget -->
                        </div><!-- end widget -->
                    </div><!-- end col -->

                    <div class="col-lg-2 col-md-12 col-sm-12 col-xs-12">
                        <div class="widget">
                            <h2 class="widget-title">Copyrights</h2>
                            <div class="link-widget">
                                <ul>
                                    <li><a href="#">About us</a></li>
                                    <li><a href="#">Advertising</a></li>
                                    <li><a href="#">Write for us</a></li>
                                    <li><a href="#">Trademark</a></li>
                                    <li><a href="#">License & Help</a></li>
                                </ul>
                            </div><!-- end link-widget -->
                        </div><!-- end widget -->
                    </div><!-- end col -->
                </div>

                <div class="row">
                    <div class="col-md-12 text-center">
                        <br>
                        <div class="copyright">&copy; Tech Blog. Design: <a href="http://html.design">HTML Design</a>.</div>
                    </div>
                </div>
            </div><!-- end container -->
        </footer><!-- end footer -->

        <div class="dmtop">Scroll to Top</div>
        
    </div><!-- end wrapper -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet"> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.4.0/css/buttons.dataTables.min.css">

    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="//cdn.datatables.net/buttons/1.4.0/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="//cdn.datatables.net/buttons/1.4.0/js/buttons.flash.min.js"></script>
    <script type="text/javascript" src="//cdn.datatables.net/buttons/1.4.0/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="//cdn.datatables.net/buttons/1.4.0/js/buttons.print.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script type="text/javascript" src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/pdfmake.min.js"></script>
    <script type="text/javascript" src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/vfs_fonts.js"></script>
  </head>
  <body>
        <div id="wrapper">
        <header class="tech-header header">
            <div class="container-fluid">
                <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
                    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="tech-index.html">
                        <%=image_tag('blog/tech-logo.png')%>
                    </a>
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <%=link_to  'Home',root_path, class: 'nav-link'%>
                            </li>
                           
                                               
                            <li class="nav-item">
                               
                                <%=link_to 'Create Article', new_article_path, class: 'nav-link'%>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">About Us</a>
                            </li>
                            <li class="nav-item">
                               <%if current_user.present?%>
                                <%= link_to "logout", destroy_user_session_path, method: :delete, class: 'nav-link' %>
                                <%else%>
                                <%=link_to 'Log In',  new_user_session_path, class: 'nav-link'%>
                                <%end%>
                            </li>
                        </ul>
                        <ul class="navbar-nav mr-2">
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fa fa-rss"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fa fa-android"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fa fa-apple"></i></a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div><!-- end container-fluid -->
        </header><!-- end market-header -->

        <% if flash[:notice] %>
            <div class="alert alert-success" id="success-alert" style="width:50%;">
              <button type="button" class="close" data-dismiss="alert">x</button>
              <strong>Success! </strong>
              <%= notice %>
            </div>
          <% end %>
          <% if flash[:error] %>
            <div class="alert alert-danger" id="success-alert" style="width:50%;">
              <button type="button" class="close" data-dismiss="alert">x</button>
              <strong>ohh no! </strong>
              <%= flash[:error] %>
            </div>
        <% end %>
         <%= yield %>
  </body>
</html>